---
- name: Create non-root users for each droplet
  hosts: all
  become: yes

  tasks:
  
    - name: Create non-root ca user for certificate-authority-server
      ansible.builtin.user:
        name: ca
        group: sudo

    - name: Create non-root openvpn user for openvpn-server
      ansible.builtin.user:
        name: openvpn
        group: sudo

    - name: Create non-root nc user for nextcloud-server
      ansible.builtin.user:
        name: nc
        group: sudo
